### ISSUE TITLE
Instance status: Wrong data after the instance restart

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#440] opened 2023-05-12 11:15 UTC
Maybe should be "-"

<img width="640" alt="image" src="https://github.com/tradingstrategy-ai/frontend/assets/49922/919d218d-1adf-4033-8b3f-86f8b14dece3">

**Comment by kenkunz** [comment] 2023-06-27 20:08
Duplicate of #452

**Closed** 2023-06-27 20:08 UTC
Labels: priority: P2, size: S
