### ISSUE TITLE
Fix frontpage layout issue on iPad

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#66] opened 2022-04-20 07:26 UTC
![image](https://user-images.githubusercontent.com/49922/164173692-43409906-a347-4647-9e8e-7615646066e6.png)

Only affects iPad. Have not been able to reproduce on other devices.

**Comment by kenkunz** [comment] 2022-06-01 21:12
Looks like this was fixed:

![IMG_EE337103D58D-1](https://user-images.githubusercontent.com/35901/171502178-6f4171fe-d3c7-49ae-8286-d8d74c7b38bc.jpeg)

I believe it was fixed by #48, specifically a62ca6336c6805501ccaa6b3b7a7c878124c76d3

@miohtama if you're still able to reproduce this, let me know what version of iPadOS you're on.

**Closed** 2022-09-22 17:40 UTC
Labels: priority: P3
